import type { DecoratorContext, EmitContext, Enum, Model, Scalar, Type } from "@typespec/compiler";
import {
  emitFile,
  isArrayModelType,
  isRecordModelType,
  navigateProgram,
  setTypeSpecNamespace,
} from "@typespec/compiler";
import { reportDiagnostic, stateKeys, $lib } from "./lib.js";

export { $lib };

export function $tsBrand(context: DecoratorContext, target: Scalar): void {
  context.program.stateMap(stateKeys.tsBrand).set(target, true);
}

setTypeSpecNamespace("Qyl.Api.Schema.Emit.TsTypes", $tsBrand);

const HEADER = "// <auto-generated/>\n// Copyright (c) 2025-2026 ancplua\n";

function isBuiltin(type: { namespace?: { name?: string; namespace?: { name?: string } } }): boolean {
  let cursor: { name?: string; namespace?: { name?: string } } | undefined = type.namespace;
  while (cursor) {
    if (cursor.name === "TypeSpec") return true;
    cursor = cursor.namespace;
  }
  return false;
}

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  const brandBlock: string[] = [];
  const modelBlock: string[] = [];
  const enumBlock: string[] = [];
  const emittedScalars = new Set<string>();

  navigateProgram(program, {
    scalar: (s) => {
      if (isBuiltin(s)) return;
      if (!program.stateMap(stateKeys.tsBrand).has(s)) return;
      if (emittedScalars.has(s.name)) return;
      emittedScalars.add(s.name);
      brandBlock.push(`export type ${s.name} = string & { readonly __brand: "${s.name}" };\n`);
    },
    enum: (e) => {
      if (isBuiltin(e)) return;
      enumBlock.push(renderEnum(e));
    },
    model: (m) => {
      if (isBuiltin(m)) return;
      if (!m.name) return;
      if (isArrayModelType(m) || isRecordModelType(m)) return;
      modelBlock.push(renderInterface(program, m));
    },
  });

  const out = [HEADER, ...brandBlock, ...enumBlock, ...modelBlock];

  const path = `${context.emitterOutputDir}/api.ts`;
  await emitFile(program, { path, content: out.join("\n") });
}

function renderEnum(e: Enum): string {
  const entries = [...e.members.values()]
    .map((m) => `  ${m.name}: "${m.value ?? m.name}"`)
    .join(",\n");
  return `export const ${e.name}Values = {\n${entries},\n} as const;\nexport type ${e.name} = typeof ${e.name}Values[keyof typeof ${e.name}Values];\n`;
}

function renderInterface(program: import("@typespec/compiler").Program, m: Model): string {
  const lines: string[] = [`export interface ${m.name} {`];
  for (const [, prop] of m.properties) {
    const t = mapType(program, prop.type);
    const q = prop.optional ? "?" : "";
    lines.push(`  ${prop.name}${q}: ${t};`);
  }
  lines.push("}\n");
  return lines.join("\n");
}

function mapType(program: import("@typespec/compiler").Program, type: Type): string {
  switch (type.kind) {
    case "Scalar": {
      const s = type as Scalar;
      if (program.stateMap(stateKeys.tsBrand).has(s)) return s.name;
      if (["int8","int16","int32","int64","uint8","uint16","uint32","uint64","float32","float64","decimal","decimal128"].includes(s.name)) return "number";
      if (s.name === "boolean") return "boolean";
      if (s.name === "bytes") return "Uint8Array";
      if (s.name === "utcDateTime" || s.name === "offsetDateTime") return "string";
      if (s.name === "plainDate" || s.name === "plainTime") return "string";
      if (s.name === "duration") return "string";
      if (s.name === "url") return "string";
      if (s.name === "string") return "string";
      if (s.baseScalar) return mapType(program, s.baseScalar);
      reportDiagnostic(program, { code: "unmapped-type", target: s, format: { name: `scalar:${s.name}` } });
      return "unknown";
    }
    case "Model":
      if (isArrayModelType(type)) return `${mapType(program, type.indexer!.value)}[]`;
      if (isRecordModelType(type)) return `Record<string, ${mapType(program, type.indexer!.value)}>`;
      return (type as { name?: string }).name ?? "unknown";
    case "Enum":
      return (type as Enum).name;
    case "ModelProperty":
      // TypeSpec 1.13 constraint-based member access (e.g. `P.id`): the property
      // reference stands for the referenced property's type.
      return mapType(program, (type as { type: Type }).type);
    case "EnumMember": {
      const m = type as { value?: string | number; name: string };
      const v = m.value ?? m.name;
      return typeof v === "number" ? String(v) : `"${v}"`;
    }
    case "Union":
      return (type as { name?: string }).name ?? "unknown";
    case "Boolean":
      return "boolean";
    case "String":
      return "string";
    case "Number":
      return "number";
    default:
      reportDiagnostic(program, { code: "unmapped-type", target: type, format: { name: type.kind } });
      return "unknown";
  }
}
